; Script generated by the HM NIS Edit Script Wizard.
; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "ConCAD"
!define PRODUCT_VERSION "3.01.00"
!define PRODUCT_PUBLISHER "ConCAD"
; ConCAD has no dedicated web site; this points at the upstream TinyCAD project
; purely for the "About" link shown in Add/Remove Programs.
!define PRODUCT_WEB_SITE "https://www.tinycad.net"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\ConCAD.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"
!define PRODUCT_INSTALLER_NAME "ConCAD_${PRODUCT_VERSION}_Production_Release.exe"

; MUI 1.67 compatible ------
!include Sections.nsh
!include "MUI2.nsh"

; For request admin rights
!include LogicLib.nsh

; Our custom dialogue
!include "AllUsersDlg.nsdinc"

; MUI (Modern User Interface) Settings
!define MUI_ABORTWARNING

; Welcome page
!insertmacro MUI_PAGE_WELCOME

; License page
!insertmacro MUI_PAGE_LICENSE "licence.rtf"

; Custom page
Page custom fnc_AllUsersDlg_Show

; Directory page
!insertmacro MUI_PAGE_DIRECTORY

; Instfiles page
!insertmacro MUI_PAGE_INSTFILES

; Finish page
!define MUI_FINISHPAGE_RUN "$INSTDIR\ConCAD.exe"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "English"
; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "${PRODUCT_INSTALLER_NAME}"

; Require admin rights on NT6+ (When UAC is turned on)
RequestExecutionLevel admin 

InstallDir "$PROGRAMFILES32\ConCAD"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""


ShowInstDetails show
ShowUnInstDetails show

Section "MainSection" SEC01

  ; If silent install then install for "all users"
  IFSilent 0 +2
    SetShellVarContext all

  
  CreateDirectory "$INSTDIR"
  SetOutPath "$INSTDIR"
  SetOverwrite ifnewer
  File "..\Release\ConCAD.exe"
  CreateDirectory "$SMPROGRAMS\ConCAD"
  CreateShortCut "$SMPROGRAMS\ConCAD\ConCAD.lnk" "$INSTDIR\ConCAD.exe"
  CreateShortCut "$DESKTOP\ConCAD.lnk" "$INSTDIR\ConCAD.exe"
  ; 
  ;	Note:  These relative paths only work correctly if you are compiling the install script from the installer sub-directory!
  ; 
  File "..\Release\libpng16.dll"
  File "..\Release\zlib.dll"
  File "..\manual\ConCAD.html"
  File "..\installer\LGPL Version 2.1.txt"
  File "..\installer\LGPL Version 3.0.txt"

  CreateShortCut "$SMPROGRAMS\ConCAD\User Manual.lnk" "$INSTDIR\ConCAD.html"

  ;
  ; NOTE: symbol libraries (library\*.TCLib) and example circuits
  ; (examples\*.dsn) are no longer bundled with the installer.
  ;

  ;
  ; Register '.con' files as 'ConCAD Design'
  ;
  WriteRegStr HKCR ".con" "" "ConCAD Design"  ; set our file association
  WriteRegStr HKCR "ConCAD Design" "" "ConCAD Design"
  WriteRegStr HKCR "ConCAD Design\shell" "" "open"
  WriteRegStr HKCR "ConCAD Design\DefaultIcon" "" "$INSTDIR\ConCAD.exe,0"
  WriteRegStr HKCR "ConCAD Design\shell\open\command" "" '"$INSTDIR\ConCAD.exe" "%1"'

  WriteRegStr HKCR "ConCAD Design\shell\edit" "" "Edit ConCAD Design"
  WriteRegStr HKCR "ConCAD Design\shell\edit" "Icon" '"$INSTDIR\ConCAD.exe",0'
  WriteRegStr HKCR "ConCAD Design\shell\edit\command" "" '"$INSTDIR\ConCAD.exe" "%1"'
  
  ; SVG title-block templates, picked from File -> Design Details -> Title Block.
  SetOutPath "$INSTDIR\templates\title-blocks"
  File "..\templates\title-blocks\Simple-A4.svg"
  File "..\templates\title-blocks\Drawing-Details.svg"

  ; Revision history table template (Edit -> Revision History).
  SetOutPath "$INSTDIR\templates"
  File "..\templates\revision.svg"
  
  ; A file purely for the purpose of setting a timestamp of when TinyCAD was installed
  FileOpen $0 "$INSTDIR\installed.txt" w
  FileClose $0

  ; Install the C++ redistributable  
  SetOutPath "$INSTDIR"
  File ".\VC_redist.x86.exe"
  ExecWait '"$INSTDIR\VC_redist.x86.exe" /passive'
  Delete "$INSTDIR\VC_redist.x86.exe"

SectionEnd

Section -AdditionalIcons
  ; ConCAD has no dedicated web site, so no "Website" shortcut is created.
  CreateShortCut "$SMPROGRAMS\ConCAD\Uninstall.lnk" "$INSTDIR\uninst.exe"
  CreateShortCut "$SMPROGRAMS\ConCAD\Users Group.lnk" "https://forum.tinycad.net"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\ConCAD.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\ConCAD.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd

Function .onInit
  UserInfo::GetAccountType
  pop $0
  ${If} $0 != "admin" ;Require admin rights on NT4+
    MessageBox mb_iconstop "Administrator rights required!"
    SetErrorLevel 740 ;ERROR_ELEVATION_REQUIRED
    Quit
  ${EndIf}
FunctionEnd

Function un.onUninstSuccess
  HideWindow
  IFSilent +2
    MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) was successfully removed from your computer."
FunctionEnd

Function un.onInit
  IFSilent +3
    MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "Are you sure you want to completely remove $(^Name) and all of its components?" IDYES +2
    Abort
FunctionEnd

Section Uninstall

  ; Determine if we installed for all users or a specific user
  IfFileExists "$SMPROGRAMS\ConCAD\ConCAD.lnk" +2 0
    SetShellVarContext all

  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"

  ; Clean up symbol libraries / examples left by older installers that
  ; bundled them (current installer no longer ships these).
  RMDir /r "$INSTDIR\library"
  RMDir /r "$INSTDIR\examples"

  Delete "$INSTDIR\ConCAD.html"
  ; legacy filename from before the ConCAD rebrand
  Delete "$INSTDIR\TinyCAD.html"

  Delete "$INSTDIR\zlib.dll"
  Delete "$INSTDIR\libpng16.dll"
  Delete "$INSTDIR\ConCAD.exe"
  Delete "$INSTDIR\installed.txt"

  Delete "$SMPROGRAMS\ConCAD\Uninstall.lnk"
  Delete "$SMPROGRAMS\ConCAD\Help.lnk"
  Delete "$DESKTOP\ConCAD.lnk"
  Delete "$SMPROGRAMS\ConCAD\Users Group.lnk"
  Delete "$SMPROGRAMS\ConCAD\ConCAD.lnk"
  Delete "$SMPROGRAMS\ConCAD\User Manual.lnk"
  Delete "$INSTDIR\LGPL Version 2.1.txt"
  Delete "$INSTDIR\LGPL Version 3.0.txt"
  Delete "$INSTDIR\templates\title-blocks\Simple-A4.svg"
  Delete "$INSTDIR\templates\title-blocks\Drawing-Details.svg"
  Delete "$INSTDIR\templates\revision.svg"

  RMDir "$SMPROGRAMS\ConCAD"
  RMDir "$INSTDIR\templates\title-blocks"
  RMDir "$INSTDIR\templates"
  RMDir "$INSTDIR"

  ;
  ; Remove the '.con' file association written on install.  Only clear
  ; '.con' if it still points at us (another program may have claimed it
  ; since), and keep the key if other entries (e.g. OpenWithProgids) remain.
  ;
  ReadRegStr $0 HKCR ".con" ""
  StrCmp $0 "ConCAD Design" 0 +3
    DeleteRegValue HKCR ".con" ""
    DeleteRegKey /ifempty HKCR ".con"
  DeleteRegKey HKCR "ConCAD Design"
  ; SHCNE_ASSOCCHANGED: refresh Explorer's cached icons/associations
  System::Call 'shell32::SHChangeNotify(i 0x08000000, i 0, p 0, p 0)'

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd
